import type { Quest } from "../types/quest";
export const dailyQuests: Quest[] = [
  {
    quest_id: "1a2b3c4d-daily-001",
    child_id: "child-uuid-001",
    type: "daily",
    name: "책 읽기",
    description: "오늘 책 5페이지 읽기",
    state: "다 했어요",
    end_date: "2025-06-05",
    created: "2025-06-01",
    isStatic: true,
    reward: 50,
    imageUrl: undefined,
  },
  {
    quest_id: "1a2b3c4d-daily-002",
    child_id: "child-uuid-001",
    type: "daily",
    name: "정리정돈",
    description: "책상 정리하기",
    state: "돈 받기",
    end_date: "2025-06-05",
    created: "2025-06-01",
    isStatic: true,
    reward: 70,
    imageUrl: undefined,
  },
  {
    quest_id: "1a2b3c4d-daily-003",
    child_id: "child-uuid-001",
    type: "daily",
    name: "양치하기",
    description: "자기 전 양치하기",
    state: "수락하기",
    end_date: "2025-06-05",
    created: "2025-06-01",
    isStatic: true,
    reward: 30,
    imageUrl: undefined,
  },
  {
    quest_id: "1a2b3c4d-daily-001",
    child_id: "child-uuid-001",
    type: "daily",
    name: "책 읽기",
    description: "오늘 책 5페이지 읽기",
    state: "다 했어요",
    end_date: "2025-06-05",
    created: "2025-06-01",
    isStatic: true,
    reward: 50,
    imageUrl: undefined,
  },
  {
    quest_id: "1a2b3c4d-daily-001",
    child_id: "child-uuid-001",
    type: "daily",
    name: "책 읽기",
    description: "오늘 책 5페이지 읽기",
    state: "기다리는 중",
    end_date: "2025-06-05",
    created: "2025-06-01",
    isStatic: true,
    reward: 50,
    imageUrl: undefined,
  },
];
